export const GRAPH_LAYOUT_LINE =  'GRAPH_LAYOUT_LINE';
export const GRAPH_LAYOUT_GRID =  'GRAPH_LAYOUT_GRID';
export const GRAPH_LAYOUT_CIRCLE =  'GRAPH_LAYOUT_CIRCLE';
export const GRAPH_LAYOUT_FORCE =  'GRAPH_LAYOUT_FORCE';
export const GRAPH_LAYOUT_TREE =  'GRAPH_LAYOUT_TREE';

export const GRAPH_TOOL_ZOOMIN =  'GRAPH_TOOL_ZOOMIN';
export const GRAPH_TOOL_ZOOMOUT =  'GRAPH_TOOL_ZOOMOUT';
export const GRAPH_TOOL_CONFIG =  'GRAPH_TOOL_CONFIG';
export const GRAPH_TOOL_SELECT =  'GRAPH_TOOL_SELECT';
export const GRAPH_TOOL_MOVING =  'GRAPH_TOOL_MOVING';

export const GRAPH_DATA_SUCCESS =  'GRAPH_DATA_SUCCESS';
export const GRAPH_DATA_FAILED =  'GRAPH_DATA_FAILED';
